[project]
name = "data-viewer"
version = "0.1.0"
description = "A Simple Data Viewer"
readme = "README.md"
authors = [
    { name = "MNIKIEMA", email = "nikiemamahamadi01@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.5.0",
    "duckdb>=1.4.4",
    "gradio>=6.5.1",
    "pandas>=3.0.0",
]

[project.scripts]
python-package-template = "data_viewer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/data_viewer"]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]


[tool.ruff]
line-length = 110
target-version = "py313"
exclude = [
    ".venv",
    "build",
    "dist",
]

[tool.ruff.lint]
select = ["E", "F", "B", "UP", "I"]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"**/*.py" = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["data_viewer"]

[tool.ruff.format]
# Use double quotes for strings.
quote-style = "double"

# Indent with spaces, rather than tabs.
indent-style = "space"

# Respect magic trailing commas.
skip-magic-trailing-comma = false

# Auto detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.pytest.ini_options]
testspath = [
    "tests"
]
addopts = "-ra -q"
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]